server:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: 'password'
  ports:
    - "13306:3306"
  volumes:
    - ./data:/var/lib/mysql:rw

client:
  image: arey/mysql-client
  links:
    - server:server
  entrypoint: mysql -hserver -uroot -ppassword